name: dart_talk
description: Sample application for my talk about Dart
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.4
  shelf: ^1.2.0
  shelf_router: ^1.1.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
